version: "3.6"

networks:
  web:
    external: true
  inside:
    external: false

services:
  traefik:
    image: traefik:v2.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - web

  ojs1:
    env_file:
      - .env.ojs1
    image: "pkpofficial/${OJS_IMAGE:-ojs}:${OJS_VERSION:-latest}"
    container_name: "ojs_app_${COMPOSE_PROJECT_NAME:-ojs1}"
    hostname: "${COMPOSE_PROJECT_NAME:-ojs1}"
    ports:
      - "${HTTP_PORT:-8081}:80"
      - "${HTTPS_PORT:-8481}:443"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./volumes_ojs1/private:/var/www/files
      - ./volumes_ojs1/public:/var/www/html/public
      - ./volumes_ojs1/config/ojs.config.inc.php:/var/www/html/config.inc.php
    networks:
      - web
      - inside
    depends_on:
      - db1
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ojs1.rule=Host(`ojs1.ojstest.ddns.net`)"
      - "traefik.http.routers.ojs1.entrypoints=web"
      - "traefik.http.services.ojs1.loadbalancer.server.port=80"

  db1:
    image: mariadb:10.2
    env_file:
      - .env.ojs1
    container_name: "ojs_db_${COMPOSE_PROJECT_NAME:-ojs1}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ojsPwd}"
      MYSQL_DATABASE: "${OJS_DB_NAME:-ojs}"
      MYSQL_USER: "${OJS_DB_USER:-ojs}"
      MYSQL_PASSWORD: "${OJS_DB_PASSWORD:-ojsPwd}"
    volumes:
      - ./volumes_ojs1/db:/var/lib/mysql
      - ./volumes_ojs1/dump:/docker-entrypoint-initdb.d
#      - ./volumes/logs/db:/var/log/mysql
#      - ./volumes/config/db.charset.conf:/etc/mysql/conf.d/charset.cnf
    networks:
      - inside
    restart: always

  ojs2:
    env_file:
      - .env.ojs2
    image: "pkpofficial/${OJS_IMAGE:-ojs}:${OJS_VERSION:-latest}"
    container_name: "ojs_app_${COMPOSE_PROJECT_NAME:-ojs2}"
    hostname: "${COMPOSE_PROJECT_NAME:-ojs2}"
    ports:
      - "${HTTP_PORT:-8082}:80"
      - "${HTTPS_PORT:-8482}:443"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./volumes_ojs2/private:/var/www/files
      - ./volumes_ojs2/public:/var/www/html/public
      - ./volumes_ojs2/config/ojs.config.inc.php:/var/www/html/config.inc.php
    networks:
      - web
      - inside
    depends_on:
      - db2
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ojs2.rule=Host(`ojs2.ojstest.ddns.net`)"
      - "traefik.http.routers.ojs2.entrypoints=web"
      - "traefik.http.services.ojs2.loadbalancer.server.port=80"

  db2:
    image: mariadb:10.2
    env_file:
      - .env.ojs2
    container_name: "ojs_db_${COMPOSE_PROJECT_NAME:-ojs2}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ojsPwd}"
      MYSQL_DATABASE: "${OJS_DB_NAME:-ojs}"
      MYSQL_USER: "${OJS_DB_USER:-ojs}"
      MYSQL_PASSWORD: "${OJS_DB_PASSWORD:-ojsPwd}"
    volumes:
      - ./volumes_ojs2/db:/var/lib/mysql
      - ./volumes_ojs2/dump:/docker-entrypoint-initdb.d
#      - ./volumes/logs/db:/var/log/mysql
#      - ./volumes/config/db.charset.conf:/etc/mysql/conf.d/charset.cnf
    networks:
      - inside
    restart: always

  ojs3:
    env_file:
      - .env.ojs3
    image: "pkpofficial/${OJS_IMAGE:-ojs}:${OJS_VERSION:-latest}"
    container_name: "ojs_app_${COMPOSE_PROJECT_NAME:-ojs3}"
    hostname: "${COMPOSE_PROJECT_NAME:-ojs3}"
    ports:
      - "${HTTP_PORT:-8083}:80"
      - "${HTTPS_PORT:-8483}:443"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./volumes_ojs3/private:/var/www/files
      - ./volumes_ojs3/public:/var/www/html/public
      - ./volumes_ojs3/config/ojs.config.inc.php:/var/www/html/config.inc.php
    networks:
      - web
      - inside
    depends_on:
      - db3
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ojs3.rule=Host(`ojs3.ojstest.ddns.net`)"
      - "traefik.http.routers.ojs3.entrypoints=web"
      - "traefik.http.services.ojs3.loadbalancer.server.port=80"

  db3:
    image: mariadb:10.2
    env_file:
      - .env.ojs3
    container_name: "ojs_db_${COMPOSE_PROJECT_NAME:-ojs3}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ojsPwd}"
      MYSQL_DATABASE: "${OJS_DB_NAME:-ojs}"
      MYSQL_USER: "${OJS_DB_USER:-ojs}"
      MYSQL_PASSWORD: "${OJS_DB_PASSWORD:-ojsPwd}"
    volumes:
      - ./volumes_ojs3/db:/var/lib/mysql
      - ./volumes_ojs3/dump:/docker-entrypoint-initdb.d
#      - ./volumes/logs/db:/var/log/mysql
#      - ./volumes/config/db.charset.conf:/etc/mysql/conf.d/charset.cnf
    networks:
      - inside
    restart: always